mainapp/urls.py
from django.urls import path
from .views import (
    ProductDetailView,
    BaseView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView
)

urlpatterns = [
    path("", BaseView.as_view(), name="home"),
    path("products/<str:ct_model>/<str:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("category/<str:slug>/", CategoryDetailView.as_view(), name="category_detail"),
    path("cart/", CartView.as_view(), name="cart"),
    path("add-to-cart/<str:ct_model>/<str:slug>/", AddToCartView.as_view(), name="add_to_cart"),
    path("remove-from-cart/<str:ct_model>/<str:slug>/", DeleteFromCartView.as_view(), name="delete_from_cart"),
    path("change-qty/<str:ct_model>/<str:slug>/", ChangeQTYView.as_view(), name="change_qty"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("make-order/", MakeOrderView.as_view(), name="make_order"),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mainapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from PIL import Image
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.utils import timezone

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={"ct_model": ct_model, "slug": obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:
    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get("with_respect_to")
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_models.model_class()._base_manager.all().order_by("-id")
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products,
                        key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                        reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Model):
    CATEGORY_NAME_COUNT_NAME = {
        "Նոթբուքեր": "notebook__count",
        "Սմարթֆոններ": "smartphone__count"
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count("notebook", "smartphone")
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Կատեգորիա")
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"slug": self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (800, 800)
    MAX_IMAGE_SIZE = 3145728

    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Կատեգորիա")
    title = models.CharField(max_length=255, verbose_name="Անվանում")
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name="Նկար")
    description = models.TextField(verbose_name="Նկարագրություն", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Գին")

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        # min_height, min_width = self.MIN_RESOLUTION
        # max_height, max_width = self.MAX_RESOLUTION
        # if img.heigth < min_height or img.width < min_width:
        #     raise MinResolutionErrorException("Նկարի չափսերը փոքր են նվազագույն չափսերից")
        # if img.heigth > max_height or img.width > max_width:
        #     raise MaxResolutionErrorException("Նկարի չափսերը մեծ են առավելագույն չափսերից")

        new_img = img.concert("RGB")
        resize_new_img = new_img.resize((800, 800), Image.ANTIALIAS)
        filestream = BytesIO()
        resize_new_img.save(filestream, "JPEG", quality=90)
        filestream.seek(0)
        name = "{}.{}".format(self.image.name.split("."))
        self.image = InMemoryUploadedFile(
            filestream, "ImageField", name, "jpeg/image", sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Անկյունագիծ")
    display_type = models.CharField(max_length=255, verbose_name="Ցուցադրման տիպ")
    processor_freq = models.CharField(max_length=255, verbose_name="Պրոցեսորի մաքրություն")
    ram = models.CharField(max_length=255, verbose_name="Օպերատիվ հիշողություն")
    video = models.CharField(max_length=255, verbose_name="Վիդեոքարտ")
    time_without_charge = models.CharField(max_length=255, verbose_name="Մարտկոցի աշխատանքի ժամանակ")

    def __str__(self):
        return f"{self.category.name} | {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Անկյունագիծ")
    display_type = models.CharField(max_length=255, verbose_name="Ցուցադրման տիպ")
    resolution = models.CharField(max_length=255, verbose_name="Էկրանի ընդլայնում")
    accum_volume = models.CharField(max_length=255, verbose_name="Մարտկոցի ծավալ")
    ram = models.CharField(max_length=255, verbose_name="Օպերատիվ հիշողություն")
    sd = models.BooleanField(default=True, verbose_name="Ներդրված SD քարտի հիշողության ծավալ")
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True,
                                     verbose_name="Մեծագույն ներդրման հիշողության ծավալ")
    main_cam_mp = models.CharField(max_length=255, verbose_name="Ետևի տեսախցիկ")
    frontal_cam_mp = models.CharField(max_length=255, verbose_name="Առջևի տեսախցիկ")

    def __str__(self):
        return f"{self.category.name} | {self.title}"

    def get_absolute_url(self):
        return get_product_url(self, "product_detail")

    # @property
    # def sd(self):
    #     if self.sd:
    #         return "Այո"
    #     return "Ոչ"


class CartProduct(models.Model):
    user = models.ForeignKey("Customer", on_delete=models.CASCADE, verbose_name="Հաճախորդ")
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE, verbose_name="Զամբյուղ", related_name="related_product")
    # product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Ապրանք")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Վերջնական գին")

    def __str__(self):
        return f"Ապրանք՝ {self.content_object.title} (զամբյուղի համար)"

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey("Customer", null=True, on_delete=models.CASCADE, verbose_name="Սեփականատեր")
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Վերջնական գին")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Գնորդ")
    phone = models.CharField(max_length=20, verbose_name="Հեռախոսահամար", null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name="Հասցե", null=True, blank=True)
    orders = models.ManyToManyField("Order", related_name="related_customer", verbose_name="Գնորդի պատվերներ")

    def __str__(self):
        return f"Գնորդ՝ {self.user.first_name} {self.user.last_name}"


class Order(models.Model):
    STATUS_NEW = "new"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_READY = "is_ready"
    STATUS_COMPLETED = "completed"
    BUYING_TYPE_SELF = "self"
    BUYING_TYPE_DELIVERY = "delivery"

    STATUS_CHOICES = (
        (STATUS_NEW, "Նոր պատվեր"),
        (STATUS_IN_PROGRESS, "Պատվերն ընթացքի մեջ է"),
        (STATUS_READY, "Պատվերը պատրաստ է"),
        (STATUS_COMPLETED, "Պատվերը ստացված է")
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, "Ինքնականչ"),
        (BUYING_TYPE_DELIVERY, "Առաքում")
    )

    customer = models.ForeignKey(Customer, related_name="related_orders", verbose_name="Գնորդ",
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name="Անուն")
    last_name = models.CharField(max_length=255, verbose_name="Ազգանուն")
    phone = models.CharField(max_length=20, verbose_name="Հեռախոսահամար")
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name="Զամբյուղ", null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name="Հասցե", null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name="Պատվերի կարգավիճակ",
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name="Պատվերի տեսակ",
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name="Պատվերի մեկնաբանություն", null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name="Պատվերի ստեղծվելու ժամանակ")
    order_date = models.DateTimeField(default=timezone.now, verbose_name="Պատվերի ստացման ժամանակ")

    def __str__(self):
        return str(self.id)

mainapp/views.py
from django.db import transaction
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.contenttypes.models import ContentType
from django.views.generic import DetailView, View
from django.contrib import messages
from .models import (
    Notebook, Smartphone, Category, LatestProducts, Customer, Cart, CartProduct
)
from .mixins import CategoryDetailMixin, CartMixin
from .forms import OrderForm
from .utils import recalc_cart


class BaseView(CartMixin, View):
    template_name = "base.html"

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page("notebook", "smartphone")
        context = {
            "categories": categories,
            "products": products,
            "cart": self.cart
        }
        return render(request, self.template_name, context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):
    CT_MODEL_MODEL_CLASS = {
        "notebook": Notebook,
        "smartphone": Smartphone,
    }
    context_object_name = "product"
    template_name = "product_detail.html"
    slug_url_kwarg = "slug"

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs["ct_model"]]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ct_model"] = self.model._meta.model_name
        context["cart"] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):
    model = Category
    queryset = Category.objects.all()
    context_object_name = "category"
    template_name = "category_detail.html"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart"] = self.cart
        return context


class AddToCartView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get("ct_model"), kwargs.get("slug")
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        if created:
            self.cart.products.add(cart_product)
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Ապրանքը հաջողությամբ ավելացվեց")
        return HttpResponseRedirect("/cart/")


class DeleteFromCartView(CartMixin, View):
    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get("ct_model"), kwargs.get("slug")
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Ապրանքը հաջողությամբ ջնջվեց")
        return HttpResponseRedirect("/cart/")


class ChangeQTYView(CartMixin, View):
    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get("ct_model"), kwargs.get("slug")
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        qty = int(request.POST.get("qty"))
        cart_product.qty = qty
        cart_product.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Քանակը հաջողությամբ փոխվեց")
        return HttpResponseRedirect("/cart/")


class CartView(CartMixin, View):
    template_name = "cart.html"

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            "cart": self.cart,
            "categories": categories
        }
        return render(request, self.template_name, context)


class CheckoutView(CartMixin, View):
    template_name = "checkout.html"

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        form = OrderForm(request.POST or None)
        context = {
            "cart": self.cart,
            "categories": categories,
            "form": form
        }
        return render(request, self.template_name, context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data["first_name"]
            new_order.last_name = form.cleaned_data["last_name"]
            new_order.phone = form.cleaned_data["phone"]
            new_order.address = form.cleaned_data["address"]
            new_order.buying_type = form.cleaned_data["buying_type"]
            new_order.order_date = form.cleaned_data["order_date"]
            new_order.comment = form.cleaned_data["comment"]
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, "Շնորհակալություն պատվերի համար")
            return HttpResponseRedirect("/")
        return HttpResponseRedirect("/checkout/")

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($) {
        $('#id_sd').on('click', function(){
            if($('#id_sd').prop('checked') == true){
                $('#id_sd_volume_max').prop('readonly', false)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'white')
            }else{
                    $('#id_sd_volume_max').prop('readonly', true)
                    $('#id_sd_volume_max').val('')
                    $('#id_sd_volume_max').css('background', 'lightgray')
                 }
        })
    })(django.jQuery);
</script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Start Bootstrap">
    <meta name="google-site-verification" content="37Tru9bxB3NrqXCt6JT5Vx8wz2AJQ0G4TkC-j8WL3kw">

    <title>
        {% block title %} {% endblock %}
    </title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


</head>
<style>
    body {
        padding-top: 56px;
    }
</style>
<body class="preview-page">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'cart' %}">
                            Զամբյուղ
                        <span class="badge badge-pill badge-danger">
                            {{ cart.products.count }}
                        </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">Shop Name</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
                    {% endfor %}
                </div>
            </div>

            <div class="col-lg-9">
                {% block content %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                <strong>{{ message }}</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carouselExampleIndicators" data-slide-to="0" class=""></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
                            <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item">
                                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                            </div>
                            <div class="carousel-item active">
                                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>

                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card h-100">
                                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                                    <div class="card-body">
                                        <h4 class="card-title">
                                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                        </h4>
                                        <h5>{{ product.price }} դրամ</h5>
                                        <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                                            <button class="btn btn-danger">Ավելացնել զամբյուղում</button>
                                        </a>
                                    </div>
<!--                                    <div class="card-footer">-->
<!--                                        <small class="text-muted">★ ★ ★ ★ ☆</small>-->
<!--                                    </div>-->
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endblock %}
            </div>
        </div>
    </div>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">© Karen Karapetyan</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>
</body>
</html>

mainapp/templates/cart.html
{% extends "base.html" %}

{% block title %}
    Cart
{% endblock %}

{% block content %}
    <h3 class="text-center mt-5 mb-5">Ձեր զամբյուղը {% if not cart.products.count %}դատարկ է{% endif %}</h3>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    {% if cart.products.count %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Անուն</th>
                    <th scope="col">Նկար</th>
                    <th scope="col">Գին</th>
                    <th scope="col">Քանակ</th>
                    <th scope="col">Ընդհանուր գին</th>
                    <th scope="col">Գործողություն</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart.products.all %}
                    <tr>
                        <th scope="row">{{ item.content_object.title }}</th>
                        <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid"></td>
                        <td>{{ item.content_object.price }} դրամ</td>
                        <td>
                            <form action="{% url 'change_qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}" method="post">
                                {% csrf_token %}
                                <input type="number" class="form-control" style="width: 70px;" min="1" name="qty" value="{{ item.qty }}">
                                <br>
                                <input type="submit" class="btn btn-primary" value="Փոխել քանակը">
                            </form>
                        </td>
                        <td>{{ item.final_price }} դրամ</td>
                        <td>
                            <a href="{% url 'delete_from_cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}">
                                <button class="btn btn-danger">Ջնջել զամբյուղից</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="2"></td>
                    <td>Ընդհանուր</td>
                    <td>{{ cart.total_products }}</td>
                    <td><strong>{{ cart.final_price }} դրամ</strong></td>
                    <td><a href="{% url 'checkout' %}">
                        <button class="btn btn-primary">Գնալ գրանցման</button>
                    </a></td>
                </tr>
            </tbody>
        </table>
    {% endif %}
{% endblock %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}
    Category Detail
{% endblock %}

{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Գլխավոր էջ</a></li>
            <li class="breadcrumb-item active">{{ category.name }}</li>
        </ol>
    </nav>

    <div class="row">
        {% for product in category_products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                        </h4>
                        <h5>{{ product.price }} դրամ</h5>
                        <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
                            <button class="btn btn-danger">Ավելացնել զամբյուղում</button>
                        </a>
                    </div>
<!--                                    <div class="card-footer">-->
<!--                                        <small class="text-muted">★ ★ ★ ★ ☆</small>-->
<!--                                    </div>-->
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}